    Running command git checkout -q 1.4.2
    error: pathspec '1.4.2' did not match any file(s) known to git
    error: subprocess-exited-with-error
    
    × git checkout -q 1.4.2 did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: 25.1.1 -> 25.2
  Notice:  To update, run: python3 -m pip install --upgrade pip
  error: subprocess-exited-with-error
  
  × git checkout -q 1.4.2 did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Traceback (most recent call last):
    File "/action/entrypoint.py", line 167, in <module>
      main()
    File "/action/entrypoint.py", line 23, in main
      install_buildozer(env["INPUT_BUILDOZER_VERSION"])
    File "/action/entrypoint.py", line 66, in install_buildozer
      subprocess.check_call(
    File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/bin/python3', '-m', 'pip', 'install', '--user', '--upgrade', 'git+https://github.com/kivy/buildozer.git@1.4.2']' returned non-zero exit status 1.
